In [8]:
from sqlalchemy import create_engine
from sqlalchemy_utils import database_exists, create_database
import psycopg2
import pandas as pd



from util import get_data
from util import mapping
from util import clean_data
from util import config
from util import plot_clusters

In [4]:
# Define a database name (we're using a dataset on births, so we'll call it birth_db)
# Set your postgres username/password, and connection specifics
username = 'postgres'
password = 'espinacas'     # change this
host     = 'localhost'
port     = '5432'            # default port that postgres listens on
db_name  = 'trips'

In [5]:
## 'engine' is a connection to a database
## Here, we're using postgres, but sqlalchemy can connect to other things too.
engine = create_engine( 'postgresql://{}:{}@{}:{}/{}'.format(username, password, host, port, db_name) )
print(engine.url)

postgresql://postgres:espinacas@localhost:5432/trips

In [6]:
## create a database (if it doesn't exist)
if not database_exists(engine.url):
    create_database(engine.url)
print(database_exists(engine.url))

True

In [9]:
df = pd.read_csv(config.PROCESSED_DATA_PATH + 'trips.csv')
print(df.shape)
df = clean_data.filter_cleaned_trips(df)
print(df.shape)

(20894, 5)
(20877, 5)

In [16]:
print(rte_id)
res = pd.read_csv(config.CLEAN_TRIPS_PATH + '{}.csv'.format(rte_id))

20246892

In [17]:
for i, rte_id in enumerate(df.id):
    if not i % 100:
        print(i)
    res = pd.read_csv(config.CLEAN_TRIPS_PATH + '{}.csv'.format(rte_id))
    res['key'] = rte_id
    if i == 0: exists_str = 'replace'
    else: exists_str = 'append'
    res.to_sql('breadcrumb_trips_table', engine, if_exists=exists_str)

0
100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300
5400
5500
5600
5700
5800
5900
6000
6100
6200
6300
6400
6500
6600
6700
6800
6900
7000
7100
7200
7300
7400
7500
7600
7700
7800
7900
8000
8100
8200
8300
8400
8500
8600
8700
8800
8900
9000
9100
9200
9300
9400
9500
9600
9700
9800
9900
10000
10100
10200
10300
10400
10500
10600
10700
10800
10900
11000
11100
11200
11300
11400
11500
11600
11700
11800
11900
12000
12100
12200
12300
12400
12500
12600
12700
12800
12900
13000
13100
13200
13300
13400
13500
13600
13700
13800
13900
14000
14100
14200
14300
14400
14500
14600
14700
14800
14900
15000
15100
15200
15300
15400
15500
15600
15700
15800
15900
16000
16100
16200
16300
16400
16500
16600
16700
16800
16900
17000
17100
17200
17300
17400
17500
17600
17700
17800
17900
18000
18100
18200
18300
18400
18500
18600
18700
18800
18900
19000
19100
19200
19300
19400
19500
19600
19700
19800
19900
20000
20100
20200
20300
20400
20500
20600
20700
20800

In [ ]:
df = pd.read_csv(config.PROCESSED_DATA_PATH + 'trips.csv')
print(df.shape)
df = clean_data.filter_cleaned_trips(df)
print(df.shape)

res = pd.read_csv(config.CLEAN_TRIPS_PATH + '{}.csv'.format(df.id[0]))
trip_xy = res.iloc[[0]][['lat', 'lon']]
# plt.plot(trip_xy.x, trip_xy.y, 'k-')
for i, rid in enumerate(df.id.tolist()):
    if i == 20: break
#     if not i % 2000: print(i)
#     if not i % 10:
    res = pd.read_csv(config.CLEAN_TRIPS_PATH + '{}.csv'.format(rid))
    trip_xy = trip_xy.append(res[['lat', 'lon']])